"""create initial tables

Revision ID: 1231410aa9e3
Revises: 
Create Date: 2025-02-03 17:09:29.314341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1231410aa9e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctor_medical_specialties_id', table_name='doctor_medical_specialties')
    op.drop_table('doctor_medical_specialties')
    op.drop_index('ix_medical_specialties_id', table_name='medical_specialties')
    op.drop_index('ix_medical_specialties_name', table_name='medical_specialties')
    op.drop_table('medical_specialties')
    op.drop_index('ix_doctors_id', table_name='doctors')
    op.drop_index('ix_doctors_name', table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('crm', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_doctors_name', 'doctors', ['name'], unique=False)
    op.create_index('ix_doctors_id', 'doctors', ['id'], unique=False)
    op.create_table('medical_specialties',
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_specialties_name', 'medical_specialties', ['name'], unique=1)
    op.create_index('ix_medical_specialties_id', 'medical_specialties', ['id'], unique=False)
    op.create_table('doctor_medical_specialties',
    sa.Column('doctor_id', sa.INTEGER(), nullable=False),
    sa.Column('medical_specialty_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['medical_specialty_id'], ['medical_specialties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_medical_specialties_id', 'doctor_medical_specialties', ['id'], unique=False)
    # ### end Alembic commands ###
